### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by marian-l** [yass-dev/Emoji-Picker#1]
How to use, the handleEmojiClick($event, emoji) method does not console.log, emit emoji or anything else?

**Comment by yass-dev** [comment]
Hello, the 'emoji_click' event emit an emoji as event.
Don't hesitate to put a star :)

**Comment by yass-dev** [comment]
Hello, the 'emoji_click' event emit an emoji as event.
Don't hesitate to put a star :)

**Comment by marian-l** [comment]
ah you need to log the event and not the emoji parameter, got it. 
also youre README.md says React.js in the Vue section, should fix that
